/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiSkillsRouteImport } from './routes/ai-skills'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as ChangedMyMindRouteImport } from './routes/changed-my-mind'
import { Route as PathToProductRouteImport } from './routes/path-to-product'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as NotesSlugRouteImport } from './routes/notes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSkillsRoute = AiSkillsRouteImport.update({
  id: '/ai-skills',
  path: '/ai-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangedMyMindRoute = ChangedMyMindRouteImport.update({
  id: '/changed-my-mind',
  path: '/changed-my-mind',
  getParentRoute: () => rootRouteImport,
} as any)
const PathToProductRoute = PathToProductRouteImport.update({
  id: '/path-to-product',
  path: '/path-to-product',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSlugRoute = NotesSlugRouteImport.update({
  id: '/notes/$slug',
  path: '/notes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-skills': typeof AiSkillsRoute
  '/certifications': typeof CertificationsRoute
  '/changed-my-mind': typeof ChangedMyMindRoute
  '/path-to-product': typeof PathToProductRoute
  '/workflow': typeof WorkflowRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/notes/': typeof NotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-skills': typeof AiSkillsRoute
  '/certifications': typeof CertificationsRoute
  '/changed-my-mind': typeof ChangedMyMindRoute
  '/path-to-product': typeof PathToProductRoute
  '/workflow': typeof WorkflowRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/notes': typeof NotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-skills': typeof AiSkillsRoute
  '/certifications': typeof CertificationsRoute
  '/changed-my-mind': typeof ChangedMyMindRoute
  '/path-to-product': typeof PathToProductRoute
  '/workflow': typeof WorkflowRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/notes/': typeof NotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-skills'
    | '/certifications'
    | '/changed-my-mind'
    | '/path-to-product'
    | '/workflow'
    | '/notes/$slug'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-skills'
    | '/certifications'
    | '/changed-my-mind'
    | '/path-to-product'
    | '/workflow'
    | '/notes/$slug'
    | '/notes'
  id:
    | '__root__'
    | '/'
    | '/ai-skills'
    | '/certifications'
    | '/changed-my-mind'
    | '/path-to-product'
    | '/workflow'
    | '/notes/$slug'
    | '/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiSkillsRoute: typeof AiSkillsRoute
  CertificationsRoute: typeof CertificationsRoute
  ChangedMyMindRoute: typeof ChangedMyMindRoute
  PathToProductRoute: typeof PathToProductRoute
  WorkflowRoute: typeof WorkflowRoute
  NotesSlugRoute: typeof NotesSlugRoute
  NotesIndexRoute: typeof NotesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-skills': {
      id: '/ai-skills'
      path: '/ai-skills'
      fullPath: '/ai-skills'
      preLoaderRoute: typeof AiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changed-my-mind': {
      id: '/changed-my-mind'
      path: '/changed-my-mind'
      fullPath: '/changed-my-mind'
      preLoaderRoute: typeof ChangedMyMindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path-to-product': {
      id: '/path-to-product'
      path: '/path-to-product'
      fullPath: '/path-to-product'
      preLoaderRoute: typeof PathToProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$slug': {
      id: '/notes/$slug'
      path: '/notes/$slug'
      fullPath: '/notes/$slug'
      preLoaderRoute: typeof NotesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiSkillsRoute: AiSkillsRoute,
  CertificationsRoute: CertificationsRoute,
  ChangedMyMindRoute: ChangedMyMindRoute,
  PathToProductRoute: PathToProductRoute,
  WorkflowRoute: WorkflowRoute,
  NotesSlugRoute: NotesSlugRoute,
  NotesIndexRoute: NotesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
